---
- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Create Tomcat group
  group:
    name: "{{ tomcat_group }}"

- name: Create Tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    home: "{{ tomcat_install_dir }}"
    shell: /bin/false

- name: Download Tomcat archive
  get_url:
    url: "{{ tomcat_url }}"
    dest: /tmp/tomcat.tar.gz

- name: Create Tomcat installation directory
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Extract Tomcat
  unarchive:
    src: /tmp/tomcat.tar.gz
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes
    creates: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

- name: Link Tomcat directory
  file:
    state: link
    src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ tomcat_install_dir }}/latest"

- name: Ensure correct permissions
  file:
    path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: Install Tomcat systemd service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable Tomcat
  systemd:
    name: tomcat
    state: started
    enabled: yes
