geoserver_version: "2.28.1"
geoserver_war_url: "https://sourceforge.net/projects/geoserver/files/GeoServer/{{ geoserver_version }}/geoserver-{{ geoserver_version }}-war.zip/download"
geoserver_install_dir: "/opt/tomcat/latest/webapps"
