---
- name: Deploy Nginx Configuration
  hosts: vm
  become: yes

  vars:
    site_name: geoserver.sutan.co.uk
    email: sutan@rekayasadata.co.uk
    app_user: geoserver

  roles:
    - apt
    - user-geoserver
    - nginx
    - nginx-https
    - tomcat
    - geoserver

  handlers:
    - import_tasks: ./handlers/nginx.yaml